#! /bin/sh

# bspc config external_rules_command "$(which external_rules)"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3
bspc monitor DP-4 -d 1 2 3

bspc config border_width         3
bspc config window_gap          18

bspc config focused_border_color	\#ed3f7f
bspc config active_border_color	  \#b3b0c0
bspc config normal_border_color   \#28222d

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
