#! /bin/sh

# bspc config external_rules_command "$(which external_rules)"

# Check if sxhkd is running and start it if not
pgrep -x sxhkd > /dev/null || sxhkd &

# Check if Picom is running, start it if not
pgrep picom > /dev/null || picom --experimental-backends --backend glx &

# Check for Wallpaper and load it
feh --bg-fill ~/Pictures/Wallpapers/Three\ Wishes\ \(Final\).png

# Same deal, for Dunst
pgrep dunst > /dev/null || dunst &

#Create 3 desktops on each monitor
bspc monitor DP-4 -d 1 2 3
bspc monitor DP-2 -d 1 2 3

# "Dwindle" style window layout
bspc config automatic_scheme longest_side

#WM dimensions
bspc config border_width           3
bspc config window_gap             18
bspc config top_padding 				   45
bspc config bottom_padding				 20
bspc config left_padding 					 20
bspc config right_padding					 20

#Window colors
bspc config focused_border_color	 \#ed3f7f
bspc config active_border_color	   \#b3b0c0
bspc config normal_border_color    \#28222d
bspc config presel_feedback_color  \#302838

bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        false
bspc config top_monocle_padding    25

#Mouse functionality (Super + Mouse Button)
bspc config pointer_action1        move
bspc config pointer_action2        resize_edge
bspc config click_to_focus         button1
bspc config swallow_first_click    false

#Some aplication specific rules (copied from a default)
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Gnome-calculator state=floating rectangle=400x600+200+200
#bspc rule -a Cava private=on

# Start Polybar (this didnt like being at the top but I cant remember why)
pgrep polybar > /dev/null || (polybar left & polybar right &)

# Start tray applets for polybar (maybe this should become integrated into a polybar init script)
pgrep nm-applet > /dev/null || nm-applet &

pgrep blueman-applet > /dev/null || blueman-applet &

